/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace arthrift
{
  public enum Status
  {
    INACTIVE = 0,
    ACTIVE = 1,
    SUSPENDED = 2,
  }
}
