development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  
production:
  adapter: mysql
  database: arthrift
  username: arthrift
  password: arthrift
  host: localhost
  
test:
  adapter: memory